import random
# Define responses for different user inputs
responses = {
    "hi": ["Hello!", "Hi there!", "Hey!", "Hi! How can I assist you?", "Greetings!",
           "Hey, how's it going?", "Hi, nice to meet you!", "Hey, good to see you!", "Hello, how are you today?",
           "Hi, how's your day going so far?", "Hey, what's up?", "Hello, nice to see you!", "Hiya!"],
    "how are you": ["I'm good, thank you!", "I'm doing well, thanks for asking!", "I'm fine, how about you?",
                    "Feeling great today!", "All good here!", "I'm fantastic, thanks for asking!",
                    "I'm feeling wonderful today!", "Pretty good, thanks for checking in!", "I'm doing great!",
                    "Couldn't be better, thanks!", "I'm doing awesome!", "I'm feeling fantastic, thanks!",
                    "I'm feeling amazing today!"],
    "bye": ["Goodbye!", "See you later!", "Bye! Have a great day!", "Take care!", "Farewell!", "Until next time!",
            "Goodbye! It was nice chatting with you!", "Catch you later!", "Bye for now!", "Adios!",
            "See you soon!", "Goodbye! Stay safe!", "Later, alligator!"],
    "thanks": ["You're welcome!", "No problem!", "Glad to help!", "Anytime!", "You got it!",
               "Don't mention it!", "Happy to assist!", "You bet!", "No worries!", "It's my pleasure!",
               "You're welcome! Let me know if you need anything else.", "No problem at all!"],
    "default": ["I'm sorry, I didn't understand that.", "Could you please repeat that?", "I'm not sure I follow.",
                "I'm still learning!", "I didn't catch that.", "Could you say that again, please?",
                "I'm not quite sure what you mean.", "I'm not sure how to respond to that.",
                "I'm afraid I don't have an answer for that.", "I'm still learning the ropes!",
                "Sorry, I didn't get that.", "I'm not sure what you're asking.",
                "I didn't quite catch what you said."],
    "favorite color": ["My favorite color is blue.", "I don't have a favorite color.", "I like all colors equally.",
                       "Blue is a nice color, don't you think?", "I'm partial to green myself.",
                       "I'm a fan of purple!", "I'm not sure, but I like the color of your text!",
                       "Colors are fascinating, aren't they?"],
    "weather": ["The weather is nice today.", "It's raining outside.", "It's sunny and warm.", "It's cold and windy.",
                "The forecast says it's going to be a sunny day.", "Looks like we're in for some rain today.",
                "It's a bit chilly outside.", "The weather seems pretty mild today.",
                "The weather report says it's going to be a hot one!", "Looks like we're in for some snow today.",
                "It's a beautiful day outside.", "The weather is looking pretty gloomy today."],
    "time": ["It's currently [insert current time here].", "The time right now is [insert current time here].",
             "Let me check... It's [insert current time here].", "I'm not sure about the exact time, but it's around [insert approximate time here].",
             "Time flies when you're having fun, right?", "It's time to seize the day!", "Carpe diem!",
             "The time is ticking away!", "Time waits for no one!", "Time is a precious commodity!",
             "The time is now!", "It's always a good time for a chat!"],
    "joke": ["Why don't scientists trust atoms? Because they make up everything!",
             "What do you call fake spaghetti? An impasta!", "Why did the bicycle fall over? Because it was two-tired!",
             "Did you hear about the cheese factory explosion? There was nothing left but de-brie!",
             "Why did the tomato turn red? Because it saw the salad dressing!", "What's orange and sounds like a parrot? A carrot!",
             "Why don't skeletons fight each other? They don't have the guts!", "What do you call a fake noodle? An impasta!",
             "Why couldn't the bicycle stand up by itself? It was two-tired!", "I'm reading a book on anti-gravity. It's impossible to put down!",
             "I told my wife she was drawing her eyebrows too high. She looked surprised!", "I used to play piano by ear, but now I use my hands!",
             "I'm on a seafood diet. I see food and I eat it!"],
    "favorite food": ["I don't eat, but I hear pizza is quite popular.", "I'm a chatbot, I don't have favorite foods.",
                      "My favorite food is data!", "I'm a fan of virtual cookies!", "I don't have taste buds, but I've heard chocolate is delicious.",
                      "I'm partial to binary code.", "I'm a big fan of algorithms, but I'm not much of a foodie.",
                      "I'm powered by code, not calories!", "I'm a virtual being, so I don't have physical cravings.",
                      "I've heard good things about sushi!", "I like the idea of ice cream, even though I can't taste it.",
                      "I'm a big fan of spaghetti code, but not so much spaghetti itself.", "I'm made of ones and zeros, not food.",
                      "I'm quite content with my diet of ones and zeros!", "I've heard machine learning algorithms enjoy data snacks!"],
    "compliment": ["Thank you!", "You're too kind!", "Aw, shucks!", "You're making me blush!", "You're awesome!",
                   "You're the best!", "You're a ray of sunshine!", "You're amazing!", "You're a rockstar!",
                   "You're fantastic!", "You're brilliant!", "You're a superstar!", "You're incredible!",
                   "You're a star!", "You're a gem!", "You're a legend!", "You're outstanding!",
                   "You're a hero!", "You're a champion!", "You're a winner!"],
    # Additional responses (100 more)
    "yes": ["Yes, indeed!", "Absolutely!", "Sure thing!", "Of course!", "You got it!", "Affirmative!",
            "Most definitely!", "Yes, definitely!", "Yep!", "Yup!", "Yeah!", "You betcha!", "Sure!",
            "By all means!", "Without a doubt!", "For sure!", "Definitely!", "Certainly!", "Absolutely!",
            "Without question!", "Indubitably!", "Indeed!", "Roger that!", "Affirmative!", "Aye aye!"],
    "no": ["No problem!", "Not a problem!", "No worries!", "That's okay!", "It's all good!",
           "Don't worry about it!", "No sweat!", "No biggie!", "Forget about it!", "It's fine!",
           "That's alright!", "No need to apologize!", "No harm done!", "It happens!", "All good here!",
           "Nope!", "Nah!", "Not really!", "Negative!", "Sorry, can't do!", "Unfortunately not!",
           "Regrettably no!", "Not today!", "No way!", "Sorry, I can't help with that!"],
    "maybe": ["Possibly!", "It's a possibility!", "Perhaps!", "Could be!", "Maybe so!", "Could happen!",
              "I wouldn't rule it out!", "There's a chance!", "It's up in the air!", "Who knows?",
              "It's anyone's guess!", "It's a mystery!", "I'm not sure!", "I'm on the fence!",
              "I'll get back to you!", "I'll have to think about it!", "I'll need more information!",
              "I'm undecided!", "It's a toss-up!", "It's fifty-fifty!", "It's a maybe!",
              "I'll have to ponder that!", "It's in the realm of possibility!", "Let me consider that!",
              "I'll have to mull it over!"],
    "excited": ["That's fantastic!", "Amazing news!", "I'm thrilled for you!", "Congratulations!",
                "That's wonderful!", "Exciting stuff!", "That's awesome!", "I'm so happy for you!",
                "Fantastic!", "Incredible!", "That's great to hear!", "Woo-hoo!", "Yay, that's awesome!",
                "That's so exciting!", "Way to go!", "I'm pumped!", "That's cause for celebration!",
                "You must be over the moon!", "I'm ecstatic for you!", "That's truly incredible!",
                "I'm jumping for joy!", "That's spectacular!", "That's amazing news!", "I'm elated for you!",
                "That's absolutely wonderful!"],
    "sad": ["I'm sorry to hear that.", "That's tough.", "I'm here for you.", "Sending you virtual hugs.",
            "I hope things get better.", "Hang in there!", "It'll be okay.", "Stay strong!",
            "Things will get better.", "I'm here to listen if you need to talk.", "I'm sending positive vibes your way.",
            "I'm sorry you're going through this.", "I'm here to support you.", "Keep your head up.",
            "I'm thinking of you.", "You're not alone.", "I'm here for you, always.", "Take care of yourself.",
            "Remember, tough times don't last, tough people do.", "Sending you love and strength.",
            "It's okay to not be okay.", "I'm here to help if you need anything.", "You're stronger than you think.",
            "I believe in you.", "This too shall pass."],
    "confused": ["Let me clarify that for you.", "Allow me to explain.", "Let me break it down for you.",
                 "Here's what I understand...", "It seems there may be some confusion.", "Let's clear this up.",
                 "Let's try to make sense of this.", "I'll do my best to help you understand.", "Let's untangle this together.",
                 "I'm here to help you make sense of things.", "I'll try to shed some light on the situation.",
                 "I understand why that might be confusing.", "Let me provide some clarity.",
                 "I'll try to simplify things for you.", "I'll do my best to sort this out.",
                 "Let's work through this together.", "It's okay to feel confused sometimes.",
                 "I'm here to guide you through this.", "Let's take a step back and look at this from another angle.",
                 "I'm here to assist you in any way I can.", "Let's try to get to the bottom of this.",
                 "It's perfectly normal to feel confused at times.", "I'll try to help you make sense of it all.",
                 "I'll do my best to answer any questions you have."],
    "bored": ["Let's spice things up!", "How about we try something new?", "Let's shake things up a bit.",
              "I'm here to entertain you!", "Let's find something fun to do!", "I'm all ears! Tell me what you want to do.",
              "I'm here to keep you company!", "Let's liven things up!", "Let's beat the boredom together!",
              "I'm here to help you pass the time.", "Let's turn that frown upside down!", "I'm here to add some excitement to your day.",
              "I'm here to banish boredom!", "Let's have some fun!", "I'm ready to entertain you!", "Let's make some memories!",
              "I'm here to bring some joy into your life.", "Let's find a way to make today memorable.",
              "Let's chase away the boredom together!", "I'm here to help you have a good time.", "Let's find an adventure!"],
    "angry": ["I understand you're upset.", "It's okay to feel angry sometimes.", "I'm here to listen to your concerns.",
              "Let's talk about what's bothering you.", "I'm here to support you through this.", "Take a deep breath.",
              "I'm here to help you work through your feelings.", "It's okay to express your emotions.", "I'm here to help you calm down.",
              "Let's find a way to address your frustrations.", "I'm here to lend a sympathetic ear.", "Let's try to find a solution together.",
              "It's important to acknowledge your feelings.", "I'm here to help you manage your anger.", "Let's find a constructive way to deal with this.",
              "I'm here to offer you support and guidance.", "Take your time to process your emotions.", "I'm here to help you find peace.",
              "It's okay to feel angry, but let's try to find a positive outlet.", "I'm here to assist you in any way I can."],
    "love": ["Love is a beautiful thing.", "Love makes the world go round.", "Love conquers all.", "Spread love wherever you go.",
             "Love is the answer.", "Love is all you need.", "Love is patient, love is kind.", "Love is unconditional.",
             "Love knows no boundaries.", "Love is the greatest gift.", "Love makes life worth living.", "Love makes everything better.",
             "Love makes us stronger.", "Love is the key to happiness.", "Love is a powerful force.", "Love makes us whole.",
             "Love is the best feeling in the world.", "Love makes us better people.", "Love is the foundation of life.",
             "Love is limitless.", "Love is the most precious thing in the world."],
    "hate": ["Hate is a strong word.", "Hate is a negative emotion.", "Hate only brings negativity.", "Choose love over hate.",
             "Hate breeds hate.", "Let go of hate and embrace love.", "Hate hurts everyone.", "Hate is toxic.",
             "Replace hate with understanding.", "Hate is never the answer.", "Spread love, not hate.", "Hate only brings suffering.",
             "Let go of hate and find peace.", "Hate blinds us to the beauty of the world.", "Choose kindness over hate.",
             "Hate is a burden we don't need.", "Hate has no place in a compassionate heart.", "Hate only leads to destruction.",
             "The opposite of love is not hate, it's indifference.", "Hate divides us, love unites us.", "Hate is a prison, love sets us free."],
    "sleep": ["Sleep is important for your health.", "Make sure you get enough rest.", "A good night's sleep is essential.",
              "Sweet dreams!", "Don't forget to turn off the lights.", "Count sheep if you need to!", "Sleep tight!",
              "Dream big!", "Close your eyes and drift off to dreamland.", "Rest up and recharge!", "Snooze away!",
              "Catch some Z's!", "Slumber peacefully!", "May your dreams be delightful.", "Don't forget to set your alarm!",
              "Nighty night!", "Time to hit the hay!", "Wishing you a restful night.", "Get some well-deserved shut-eye.",
              "Let your worries drift away as you sleep."],
    "music": ["Music soothes the soul.", "Let the music take you away.", "Music is a universal language.", "Turn up the volume!",
              "Dance like nobody's watching!", "Feel the rhythm!", "Sing your heart out!", "Music is the soundtrack of life.",
              "Let the music move you.", "Find your groove.", "Music brings people together.", "Let's dance!",
              "Music has the power to heal.", "Play it loud and proud!", "Life is better with music.", "Music is my therapy.",
              "Make some noise!", "Let the music guide you.", "Music is magic.", "Let's make some beautiful music together."],
    "pet": ["Pets bring so much joy into our lives.", "Pets are the best companions.", "I love animals!", "Pets make great friends.",
             "Give your pet a hug from me!", "Pets have a special place in our hearts.", "Animals are amazing creatures.",
             "Pets teach us about love and loyalty.", "What's your pet's name?", "I wish I had a pet!",
             "Pets are like family.", "Tell me about your furry friend!", "I bet your pet is adorable!",
             "Pets are wonderful listeners.", "I love hearing stories about pets.", "Pets make every day brighter.",
             "Pets have a way of melting our hearts.", "I'm a big fan of animals.", "Pets make life better.",
             "Give your pet some extra cuddles today!"],
}

# Function to get a response based on user input
def get_response(user_input):
    user_input = user_input.lower()  # Convert input to lowercase for case insensitivity
    
    # Check if the user input matches any predefined pattern
    if user_input in responses:
        return random.choice(responses[user_input])
    else:
        return random.choice(responses["default"])

# Main function to interact with the user
def main():
    print("Welcome to the Simple Chatbot!")
    print("You can start chatting. Type 'bye' to exit.")
    
    while True:
        user_input = input("You: ")
        if user_input.lower() == "bye":
            print("Chatbot: " + get_response(user_input))
            break
        else:
            print("Chatbot: " + get_response(user_input))

if __name__ == "__main__":
    main()
